### ISSUE TITLE
Kanji to katakana conversion

### ISSUE THREAD

**Issue by gonzales-gerald** [caguiclajmg/WanaKanaSharp#2]
Hi,

Can this handle Kanji to Katakana conversion? I don't see any example or documentation.

Thank you!

**Comment by caguiclajmg** [comment]
Hi @gonzales-gerald, I've decided to pick up this project again so it will be receiving updates.

However, Kanji to Katakana is not supported in [WanaKana](https://github.com/WaniKani/WanaKana) which this project is a port of, so it's highly unlikely this project will have that feature (unless WanaKana is updated to have it).

EDIT: I just saw the README said that it translated **Kanji**, Hiragana, Katakana and Romaji. I'm sorry about this confusion, this library does not handle Kanji. This has now been corrected.

**Comment by andy840119** [comment]
Try to use `Lucene.Net.Analysis.Ja` can convert kanji into katakana.
